plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'lib/omniauth-soundcloud.rb'
    - 'lib/omniauth-soundcloud2.rb'
    - 'tmp/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/omniauth/strategies/soundcloud.rb'
    - 'test/rails_integration_test.rb'
    - 'test/omniauth_soundcloud_test.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'lib/omniauth/soundcloud/version.rb'
    - 'lib/omniauth-soundcloud/version.rb'
    - 'lib/omniauth-soundcloud2/version.rb'
    - 'test/**/*'

Naming/FileName:
  Exclude:
    - 'lib/omniauth-soundcloud2.rb'

Style/OneClassPerFile:
  Exclude:
    - 'test/rails_integration_test.rb'

Minitest/MultipleAssertions:
  Exclude:
    - 'test/rails_integration_test.rb'
    - 'test/omniauth_soundcloud_test.rb'
